import type { Metadata } from "next";
import {Commissioner} from "next/font/google";
import "../src/app/styles/globals.scss";
import {MainMenu} from "@/src/features/main-menu";
import React, {Suspense} from "react";
import Loading from "@/app/loading";
import {Header} from "@/src/widges/header";
import clsx from "clsx";
import {Footer} from "@/src/shared/ui/footer";

const font = Commissioner({
    subsets: ["latin", "cyrillic"],
    display: "block"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="ru">
        <body className={clsx(font.className, "page-layout")}>
            <div className="content-wrapper">
                <Header/>
            </div>
            <div className="main-content-block content-wrapper content-container">
                <aside>
                    <MainMenu/>
                </aside>
                <Suspense fallback={<Loading/>}>
                    {children}
                </Suspense>
            </div>
            <Footer/>
        </body>
    </html>
  );
}
